plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(JavaCompile) {
    options.compilerArgs.addAll(['--release', '21'])
}

repositories {
    mavenCentral()
}

javafx {
    version = '21.0.2'
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    implementation 'com.mysql:mysql-connector-j:9.0.0'
    implementation 'org.mindrot:jbcrypt:0.4'        //The encryption dependency
    implementation 'com.zaxxer:HikariCP:7.0.2'      // The hikariCP implementation (for connection pool to enable effective multi-threading)
}

application {
    mainClass = 'com.amusementpark.MainApp'
}

test {
    useJUnitPlatform()
}